// <auto-generated />
namespace fsharp_ef.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Contexto.Context>)>]
[<Migration("20210520215733_Increment")>]
type Increment() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.AddColumn<string>(
            name = "Telefone"
            ,table = "Pessoas"
            ,``type`` = "nvarchar(max)"
            ,nullable = true
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropColumn(
            name = "Telefone"
            ,table = "Pessoas"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.3")
            |> ignore

        modelBuilder.Entity("Contexto+Pessoa", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<int>("Idade")
                .IsRequired()
                .HasColumnType("int") |> ignore
            b.Property<string>("Nome")
                .HasColumnType("nvarchar(max)") |> ignore
            b.Property<string>("Telefone")
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Pessoas") |> ignore

        )) |> ignore

