// <auto-generated />
namespace fsharp_ef.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Contexto.Context>)>]
[<Migration("20210520193229_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Pessoas"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    ).Annotation("SqlServer:Identity", "1, 1")
                Nome =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "nvarchar(max)"
                    )
                Idade =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    )
            |})
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Pessoas", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Pessoas"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder

            .UseIdentityColumns().HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.3")
            |> ignore

        modelBuilder.Entity("Contexto+Pessoa", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                .UseIdentityColumn() |> ignore
            b.Property<int>("Idade")
                .IsRequired()
                .HasColumnType("int") |> ignore
            b.Property<string>("Nome")
                .HasColumnType("nvarchar(max)") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Pessoas") |> ignore

        )) |> ignore

